[env]
TERM = "alacritty"

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_padding = true
opacity = 1.0
# stortup_mode = "Windowed"
title = "alacritty"
dynamic_title = true
resize_increments = false

[window.dimensions]
columns = 0
lines = 0

# [window.position]treo
# x = 0
# y = 0

[window.padding]
x = 0
y = 0

# [window.class]
# instance = "Alacritty"
# general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 7.5
builtin_box_drawing = false

[font.normal]
family = "JetBrainsMonoNLNerdFontMono"
style = "Regular"

[font.bold]
# family = "monospace"
style = "Bold"

[font.italic]
# family = "monospace"
style = "Italic"

[font.bold_italic]
# family = "monospace"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "Off"

[general]
live_config_reload = true
import = ["/home/main/.config/alacritty/themes/themes/github_dark_default.toml"]
# draw_bold_text_with_bright_colors = false
